steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - gcr.io/$PROJECT_ID/billwise:latest
      - --tag
      - gcr.io/$PROJECT_ID/billwise:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/billwise:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - billwise
      - --image
      - gcr.io/$PROJECT_ID/billwise:latest
      - --region
      - us-central1
      - --platform
      - managed

images:
  - gcr.io/$PROJECT_ID/billwise:latest
